name: Release
# Controls when the workflow will run
on:
  release:
    types: [published]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Log in to registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u USERNAME --password-stdin    
      - name: pull image
        run: docker pull ghcr.io/elan8/propanedb-base-alpine   
      - name: Build Docker for production
        run: ./scripts/buildDockerProd.sh
      - name: Tag 
        run: docker tag ghcr.io/elan8/propanedb ghcr.io/elan8/propanedb:${{ GITHUB_REF }}
      - name: Push 
        run: docker push ghcr.io/elan8/propanedb:${{ GITHUB_REF }}
   
